### ISSUE TITLE
"Exception" Error Message during installation

### ISSUE THREAD

**Issue by Cerfestas** [x360ce/x360ce#163] opened 2015-07-02 22:02 UTC
Hello,

I am having an issue with installing the program to use with Logitech Dual Action Controller. The error I get is as follows:

System.IO.FileNotFoundException: C:\Windows\System32\x360ce_x64.exe
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at x360ce.Engine.Data.Game.FromDisk(String fileName)
   at x360ce.App.SettingsFile.Load()
   at x360ce.App.Controls.GameSettingsUserControl.InitDefaultList()
   at x360ce.App.Controls.GameSettingsUserControl..ctor()
   at x360ce.App.MainForm.InitializeComponent()
   at x360ce.App.MainForm..ctor()
   at x360ce.App.Program.Main(String[] args)

How should I proceed?

**Comment by Squall-Leonhart** [comment] 2015-07-03 12:48
This is a duplicate of an issue already open.

**Closed as completed by Squall-Leonhart** 2015-07-03 12:48 UTC
Labels: duplicate
