### ISSUE TITLE
打不开

### ISSUE THREAD

**Issue by 406395647** [x360ce/x360ce#676] opened 2017-09-26 16:15 UTC
启动不了
![qq 20170927001256](https://user-images.githubusercontent.com/32306014/30871304-f3a12d7a-a318-11e7-86b8-bd37a2663995.png)

**Comment by Squall-Leonhart** [comment] 2017-10-27 12:39
not a but report, and probably a duplicate of an already fixed issue.

**Closed as completed by Squall-Leonhart** 2017-10-27 12:39 UTC
