### ISSUE TITLE
Canno't open the exe :(

### ISSUE THREAD

**Issue by dacolgod** [x360ce/x360ce#300] opened 2015-12-04 18:13 UTC
I got this error: 
![fodeu](https://cloud.githubusercontent.com/assets/16156442/11597266/e722215c-9aa1-11e5-9b3d-0001401ed739.png)

**Comment by Squall-Leonhart** [comment] 2015-12-13 07:50
duplicate of every other issue where the user hasn't installed dot net.

**Closed as completed by Squall-Leonhart** 2015-12-13 07:50 UTC
